apiVersion: jabos.io/v1
kind: GitRepository
metadata:
  name: first-repo
  namespace: example-env
spec:
  url: https://github.com/srfrnk/jabos-examples.git
  branch: main
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: registry.kube-system:80/example-image
---
apiVersion: jabos.io/v1
kind: JsonnetManifest
metadata:
  name: simple-jsonnet-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/manifests
  targetNamespace: example-env
  commitTLAKey: latestCommitId
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-hub-public
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: jabos/example-image-public
  dockerHub:
    secret: docker-hub
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-hub-private
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: jabos/example-image-private
  dockerHub:
    secret: docker-hub
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-gcr
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: gcr.io/jabos-331114/example-image
  gcp:
    secret: gcp
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-artifact-registry
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: europe-west2-docker.pkg.dev/jabos-331114/jabos/example-image
  gcp:
    secret: gcp
