apiVersion: v1
kind: Namespace
metadata:
  name: simple-example-build-env
---
apiVersion: v1
kind: Namespace
metadata:
  name: simple-example-runtime-env
---
apiVersion: jabos.io/v1
kind: GitRepository
metadata:
  name: first-repo
  namespace: simple-example-build-env
spec:
  url: https://github.com/srfrnk/jabos-examples.git
  branch: main
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image
  namespace: simple-example-build-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: registry.kube-system:80/example-image
---
apiVersion: jabos.io/v1
kind: JsonnetManifest
metadata:
  name: simple-jsonnet-manifest
  namespace: simple-example-build-env
spec:
  gitRepository: first-repo
  path: simple-runtime/manifests
  targetNamespace: simple-example-runtime-env
  commitTLAKey: latestCommitId
