apiVersion: jabos.io/v1
kind: GitRepository
metadata:
  name: first-repo
  namespace: example-env
spec:
  url: https://github.com/srfrnk/jabos-examples.git
  branch: main
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-build/images
  imageName: registry.kube-system:80/example-image
---
apiVersion: jabos.io/v1
kind: JsonnetManifest
metadata:
  name: simple-jsonnet-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-build/manifests
  targetNamespace: example-env
  commitTLAKey: latestCommitId
