apiVersion: jabos.io/v1
kind: GitRepository
metadata:
  name: first-repo
  namespace: example-env
spec:
  url: https://github.com/srfrnk/jabos-examples.git
  branch: main
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: registry.kube-system:80/example-image-dev
---
apiVersion: jabos.io/v1
kind: JsonnetManifest
metadata:
  name: simple-jsonnet-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/manifests
  targetNamespace: example-env
  commitTLAKey: latestCommitId
  cleanupPolicy: Delete
  tlas:
    env: dev
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-hub-public
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: jabos/example-image-public
  dockerHub:
    secret: docker-hub
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-hub-private
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: jabos/example-image-private
  dockerHub:
    secret: docker-hub
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-gcr
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: gcr.io/jabos-331114/example-image
  gcp:
    secret: gcp
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-artifact-registry
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: europe-west2-docker.pkg.dev/jabos-331114/jabos/example-image
  gcp:
    secret: gcp
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-ecr
  namespace: example-env
spec:
  gitRepository: first-repo
  contextPath: simple-runtime/images
  imageName: 524835905417.dkr.ecr.eu-west-2.amazonaws.com/example-image
  aws:
    secret: aws
---
apiVersion: jabos.io/v1
kind: PlainManifest
metadata:
  name: simple-plain-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/plain-manifests
  targetNamespace: example-env
  replacementPrefix: "\\*\\*"
  replacementSuffix: "\\*\\*"
  commitReplacementString: LATEST_COMMIT_ID
  cleanupPolicy: Delete
  replacements:
    env: dev
---
apiVersion: jabos.io/v1
kind: HelmTemplateManifest
metadata:
  name: simple-helm-template-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/helm-template
  targetNamespace: example-env
  commitValueKey: LATEST_COMMIT_ID
  cleanupPolicy: Delete
  values:
    env: dev
---
apiVersion: jabos.io/v1
kind: KustomizeManifest
metadata:
  name: simple-kustomize-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/kustomize
  targetNamespace: example-env
  dockerImages:
    - first-image
    - first-image-docker-hub-public
    - first-image-docker-hub-private
  cleanupPolicy: Delete
  replacementPrefix: "\\*\\*"
  replacementSuffix: "\\*\\*"
  replacements:
    env: dev
---
apiVersion: jabos.io/v1
kind: GitRepository
metadata:
  name: first-repo-1
  namespace: example-env-stg
spec:
  url: https://github.com/srfrnk/jabos-examples.git
  branch: stg
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-1
  namespace: example-env-stg
spec:
  gitRepository: first-repo-1
  contextPath: simple-runtime/images
  imageName: registry.kube-system:80/example-image-stg
---
apiVersion: jabos.io/v1
kind: JsonnetManifest
metadata:
  name: simple-jsonnet-manifest-1
  namespace: example-env-stg
spec:
  gitRepository: first-repo-1
  path: simple-runtime/manifests
  targetNamespace: example-env-stg
  commitTLAKey: latestCommitId
  cleanupPolicy: Delete
  tlas:
    env: stg
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-reuse-dev
  namespace: example-env-stg
spec:
  gitRepository: first-repo-1
  contextPath: simple-runtime/images
  imageName: registry.kube-system:80/example-image-dev
  build: false
---
apiVersion: jabos.io/v1
kind: JsonnetManifest
metadata:
  name: simple-jsonnet-manifest-reuse-dev
  namespace: example-env-stg
spec:
  gitRepository: first-repo-1
  path: simple-runtime/manifests
  targetNamespace: example-env-stg
  commitTLAKey: latestCommitId
  cleanupPolicy: Delete
  tlas:
    env: dev
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-hub-public-reuse-dev
  namespace: example-env-stg
spec:
  gitRepository: first-repo-1
  contextPath: simple-runtime/images
  imageName: jabos/example-image-public
  dockerHub:
    secret: docker-hub
  build: false
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-hub-private-reuse-dev
  namespace: example-env-stg
spec:
  gitRepository: first-repo-1
  contextPath: simple-runtime/images
  imageName: jabos/example-image-private
  dockerHub:
    secret: docker-hub
  build: false
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-gcr-reuse-dev
  namespace: example-env-stg
spec:
  gitRepository: first-repo-1
  contextPath: simple-runtime/images
  imageName: gcr.io/jabos-331114/example-image
  gcp:
    secret: gcp
  build: false
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-artifact-registry-reuse-dev
  namespace: example-env-stg
spec:
  gitRepository: first-repo-1
  contextPath: simple-runtime/images
  imageName: europe-west2-docker.pkg.dev/jabos-331114/jabos/example-image
  gcp:
    secret: gcp
  build: false
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-docker-ecr-reuse-dev
  namespace: example-env-stg
spec:
  gitRepository: first-repo-1
  contextPath: simple-runtime/images
  imageName: 524835905417.dkr.ecr.eu-west-2.amazonaws.com/example-image
  aws:
    secret: aws
  build: false
---
apiVersion: jabos.io/v1
kind: GitRepository
metadata:
  name: first-repo-promoted
  namespace: example-env-stg
spec:
  url: https://github.com/srfrnk/jabos-examples.git
  promotedCommit: 8377784bf9750f86e1ee947aba0f9a3c1dbece18
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image-promoted
  namespace: example-env-stg
spec:
  gitRepository: first-repo-promoted
  contextPath: simple-runtime/images
  imageName: registry.kube-system:80/example-image-promoted
---
apiVersion: jabos.io/v1
kind: Cdk8sManifest
metadata:
  name: cdk8s-go-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/cdk8s-go-manifests
  targetNamespace: example-env
  commitEnvKey: LATEST_COMMIT_ID
  cleanupPolicy: Delete
  env:
    BUILD_ENV: dev
---
apiVersion: jabos.io/v1
kind: Cdk8sManifest
metadata:
  name: cdk8s-java-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/cdk8s-java-manifests
  targetNamespace: example-env
  commitEnvKey: LATEST_COMMIT_ID
  cleanupPolicy: Delete
  env:
    BUILD_ENV: dev
---
apiVersion: jabos.io/v1
kind: Cdk8sManifest
metadata:
  name: cdk8s-python-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/cdk8s-python-manifests
  targetNamespace: example-env
  commitEnvKey: LATEST_COMMIT_ID
  cleanupPolicy: Delete
  env:
    BUILD_ENV: dev
---
apiVersion: jabos.io/v1
kind: Cdk8sManifest
metadata:
  name: cdk8s-ts-manifest
  namespace: example-env
spec:
  gitRepository: first-repo
  path: simple-runtime/cdk8s-ts-manifests
  targetNamespace: example-env
  commitEnvKey: LATEST_COMMIT_ID
  cleanupPolicy: Delete
  env:
    BUILD_ENV: dev
