apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deployment-helm-template
  name: test-deployment-helm-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment-helm-template
  template:
    metadata:
      labels:
        app: test-deployment-helm-template
    spec:
      containers:
        - image: registry.kube-system:80/example-image-{{ .Values.env }}:{{ .Values.LATEST_COMMIT_ID }}
          name: test-deployment-helm-template
